//! Roblox class reflection from a bundled, trimmed API dump.
//!
//! `data/api-dump.min.json` is regenerated by `data/build_api_dump.py` from Roblox's
//! own published API dump. `get_class_info` answers "what can I read, write, or call on
//! class X" without a live Studio by walking the class's superclass chain. The dump is a
//! snapshot, so a member added by a very recent Studio update can be missing until the
//! file is regenerated; that is the documented trade-off for a tool that needs no Studio
//! and no API key.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashSet};
use std::sync::OnceLock;

const API_DUMP: &str = include_str!("../data/api-dump.min.json");

/// The dump marks the top of the class hierarchy with this sentinel superclass.
const ROOT_SUPERCLASS: &str = "<<<ROOT>>>";
/// A valid dump is acyclic; this only guards against a malformed file looping forever.
const MAX_INHERITANCE_DEPTH: usize = 64;
/// How many near-matches to offer when a class name is not found.
const MAX_SUGGESTIONS: usize = 10;

#[derive(Deserialize)]
struct Dump {
    classes: BTreeMap<String, RawClass>,
}

#[derive(Deserialize)]
struct RawClass {
    superclass: Option<String>,
    members: Vec<Member>,
}

#[derive(Deserialize, Serialize, Clone)]
struct Param {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    name: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    value_type: Option<String>,
}

#[derive(Deserialize, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct Member {
    name: String,
    /// Property, Function, Event, or Callback.
    kind: String,
    /// Value type for a property, return type for a function. Absent for events.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    value_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    params: Option<Vec<Param>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    tags: Option<Vec<String>>,
    /// Present only when access is restricted (a plugin- or Roblox-only member).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    security: Option<String>,
    /// The superclass a member was inherited from. Absent on the queried class's own members.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    inherited_from: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ClassInfo {
    class: String,
    /// The class and each superclass up to the root, nearest first.
    inheritance: Vec<String>,
    member_count: usize,
    members: Vec<Member>,
}

fn dump() -> &'static Dump {
    static DUMP: OnceLock<Dump> = OnceLock::new();
    DUMP.get_or_init(|| serde_json::from_str(API_DUMP).expect("bundled api dump is valid json"))
}

fn not_found(dump: &Dump, class_name: &str) -> String {
    let needle = class_name.to_lowercase();
    let suggestions: Vec<&str> = dump
        .classes
        .keys()
        .filter(|name| name.to_lowercase().contains(&needle))
        .take(MAX_SUGGESTIONS)
        .map(String::as_str)
        .collect();
    if suggestions.is_empty() {
        format!("unknown class \"{class_name}\". Class names are case-sensitive, for example \"Part\" or \"Humanoid\".")
    } else {
        format!(
            "unknown class \"{class_name}\". Did you mean: {}?",
            suggestions.join(", ")
        )
    }
}

/// Resolve a class's members, optionally including inherited ones, with simple filters.
/// Returns pretty JSON on success or a human-readable error string.
pub fn class_info(
    class_name: &str,
    include_inherited: bool,
    member_kind: Option<&str>,
    name_filter: Option<&str>,
) -> Result<String, String> {
    let dump = dump();
    if !dump.classes.contains_key(class_name) {
        return Err(not_found(dump, class_name));
    }

    let mut inheritance = Vec::new();
    let mut members = Vec::new();
    let mut seen = HashSet::new();
    let mut current = Some(class_name.to_string());

    for _ in 0..MAX_INHERITANCE_DEPTH {
        let Some(name) = current else { break };
        if name == ROOT_SUPERCLASS {
            break;
        }
        let Some(class) = dump.classes.get(&name) else {
            break;
        };
        inheritance.push(name.clone());
        for member in &class.members {
            // The chain runs child first, so a member already seen was overridden lower down.
            if !seen.insert(member.name.clone()) {
                continue;
            }
            let mut resolved = member.clone();
            if name != class_name {
                resolved.inherited_from = Some(name.clone());
            }
            members.push(resolved);
        }
        if !include_inherited {
            break;
        }
        current = class.superclass.clone();
    }

    if let Some(kind) = member_kind {
        members.retain(|member| member.kind.eq_ignore_ascii_case(kind));
    }
    if let Some(filter) = name_filter {
        let needle = filter.to_lowercase();
        members.retain(|member| member.name.to_lowercase().contains(&needle));
    }
    members.sort_by(|a, b| a.kind.cmp(&b.kind).then_with(|| a.name.cmp(&b.name)));

    let info = ClassInfo {
        class: class_name.to_string(),
        inheritance,
        member_count: members.len(),
        members,
    };
    Ok(serde_json::to_string_pretty(&info).unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_dump_parses() {
        // Forces the embedded JSON through serde so a bad regenerate fails the build's tests.
        assert!(!dump().classes.is_empty());
    }

    #[test]
    fn part_inherits_basepart_properties() {
        let json = class_info("Part", true, Some("Property"), None).expect("Part exists");
        // Anchored and Size live on BasePart; Part must surface them through inheritance.
        assert!(json.contains("\"Anchored\""));
        assert!(json.contains("\"Size\""));
        assert!(json.contains("\"inheritedFrom\": \"BasePart\""));
    }

    #[test]
    fn own_members_only_when_inheritance_off() {
        let json = class_info("Part", false, None, None).expect("Part exists");
        assert!(!json.contains("\"inheritedFrom\""));
    }

    #[test]
    fn unknown_class_suggests() {
        let err = class_info("Prt", true, None, None).unwrap_err();
        assert!(err.contains("Part"));
    }
}
